name: 'Setup Chrome and ChromeDriver'
description: 'Setup Chrome via browser actions and ChromeDriver via WebDriverManager'
inputs:
  version:
    description: 'Chrome version'
    required: false
    default: 'stable'
runs:
  using: "composite"
  steps:
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: ${{ inputs.version }}
    - name: Setup ChromeDriver
      run: |
        sudo mv $(which chrome) /usr/bin/google-chrome
        wget -q https://github.com/bonigarcia/webdrivermanager/releases/download/webdrivermanager-5.1.0/webdrivermanager-5.1.0-fat.jar
        java -jar webdrivermanager-5.1.0-fat.jar resolveDriverFor chrome
        sudo mv chromedriver /usr/bin/chromedriver
        google-chrome --version
        chromedriver --version
      shell: bash
