name: Dispatch

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  check_javascript:
    uses: ./.github/workflows/should-workflow-run.yml
    with:
      bazel-target-prefix: '//javascript'

  run_javascript:
    uses: ./.github/workflows/javascript.yml
    needs: check_javascript
    if: ${{ needs.check_ruby.outputs.result == 'true' }}
