name: JavaScript workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    # Skip job based on the commit message, only works in push to branches for now
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Start XVFB
        run: Xvfb :99 &
      - name: Run JavaScript tests on Firefox
        run: bazel test //javascript/node/selenium-webdriver:tests
        env:
          DISPLAY: :99
          SELENIUM_BROWSER: firefox
